import { test,expect } from '@playwright/test';
test('storefront renders, searches, filters and has no horizontal overflow',async({page},testInfo)=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('heading',{name:'Made by hand. Held by heart.'})).toBeVisible();await expect(page.getByRole('img',{name:'A warm, sunlit home filled with natural textures and thoughtfully crafted objects'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`test-results/home-${testInfo.project.name}.png`,fullPage:true});await page.getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('textbox',{name:'Search products'}).fill('mug');await page.getByRole('button',{name:'Search',exact:true}).click();await expect(page.getByRole('heading',{name:'The Everyday Mug'})).toBeVisible();await page.getByRole('button',{name:'Filters',exact:true}).click();await page.getByLabel('Maximum price').selectOption('150000');await expect(page.getByRole('heading',{name:'The Everyday Mug'})).toBeVisible();await page.getByLabel('Search collection').fill('nothingmatchesxyz');await expect(page.getByRole('heading',{name:'A little too specific?'})).toBeVisible();expect(errors).toEqual([]);
});
test('guest personalizes a piece, checks out and pays with the development provider',async({page},testInfo)=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/products/a-name-to-remember');await expect(page.getByRole('heading',{name:'A Name to Remember',exact:true})).toBeVisible();await page.getByLabel('A name or a few meaningful words').fill('For Meera');await page.getByRole('button',{name:'Terracotta',exact:true}).click();await page.getByRole('button',{name:'Add to bag',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('dialog').getByText('For Meera')).toBeVisible();await page.getByRole('link',{name:'Continue to checkout'}).click();await page.getByLabel('Email address').fill('e2e.guest@example.com');await page.getByRole('button',{name:'Continue',exact:true}).click();for(const [name,value] of Object.entries({'Full name':'Meera Verification','Phone number':'9876543210','Address line 1':'24 Verification Garden','City':'Bengaluru','State':'Karnataka','PIN code':'560001'}))await page.getByLabel(name,{exact:true}).fill(value);await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('A little thank-you code').fill('WELCOME10');await page.getByRole('button',{name:'Continue to payment'}).click();await expect(page.getByRole('heading',{name:'One last thoughtful step.'})).toBeVisible();await page.getByRole('button',{name:/^Pay ₹/}).click();await expect(page.getByRole('heading',{name:'Development payment'})).toBeVisible();await page.getByRole('button',{name:'Simulate successful payment'}).click();await expect(page.getByRole('heading',{name:'Good things are on their way.'})).toBeVisible();await page.screenshot({path:`test-results/order-${testInfo.project.name}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(errors).toEqual([]);
});
test('admin signs in, edits a product, and processes a paid order',async({page},testInfo)=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:3001/login');await page.getByLabel('Work email').fill('admin@mitti.local');await page.getByLabel('Password',{exact:true}).fill('Crafted!Dev2026');await page.getByRole('button',{name:'Enter your workspace'}).click();await expect(page.getByRole('heading',{name:'A good day to make good things.'})).toBeVisible();await page.screenshot({path:`test-results/admin-${testInfo.project.name}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);if(testInfo.project.name!=='desktop')await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('link',{name:'Products',exact:true}).click();await page.getByRole('textbox',{name:'Search products, makers, or SKUs…'}).fill('Everyday Mug');await page.getByRole('link',{name:/The Everyday Mug Neer/}).click();await page.getByLabel('Short description').fill('Wheel-thrown stoneware');await page.getByRole('button',{name:'Save product',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Your piece has been saved.');await page.screenshot({path:`test-results/editor-${testInfo.project.name}.png`,fullPage:true});await page.goto('http://localhost:3001/orders');await page.getByPlaceholder('Search orders or customers…').fill('e2e.guest');await page.getByRole('button',{name:/^MT-/}).first().click();await page.getByLabel('Next step').selectOption('PROCESSING');await page.getByRole('button',{name:'Update order'}).click();await expect(page.getByRole('dialog').getByText('processing',{exact:true})).toBeVisible();expect(errors).toEqual([]);
});
