import { beforeAll,describe,it,expect } from 'vitest';
import { randomUUID } from 'node:crypto';
const base=process.env.TEST_API_URL||'http://localhost:4000';
const origin='http://localhost:3000';
class Client {
  cookies=new Map<string,string>();
  async call(path:string,method='GET',body?:unknown,extra:Record<string,string>={}){const response=await fetch(`${base}/${path}`,{method,headers:{Origin:origin,'Content-Type':'application/json',Cookie:[...this.cookies].map(([k,v])=>`${k}=${v}`).join('; '),...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});for(const cookie of response.headers.getSetCookie()){const [pair]=cookie.split(';');const at=pair.indexOf('=');this.cookies.set(pair.slice(0,at),pair.slice(at+1));}return {status:response.status,body:await response.json(),headers:response.headers};}
}
const admin=new Client(),guest=new Client(),stranger=new Client();let product:any,order:any;const unique=Date.now().toString(36);const address={name:'Verification Customer',phone:'9876543210',line1:'24 Test Garden Road',city:'Bengaluru',state:'Karnataka',postalCode:'560001',country:'IN'};
beforeAll(async()=>{const result=await admin.call('auth/login','POST',{email:process.env.SEED_ADMIN_EMAIL||'admin@mitti.local',password:process.env.SEED_ADMIN_PASSWORD||'Crafted!Dev2026'});expect(result.status).toBe(201);});
describe.sequential('real PostgreSQL commerce and access boundaries',()=>{
  it('has healthy database and cache connections',async()=>{expect((await guest.call('health')).body.status).toBe('ok');});
  it('denies unauthenticated operations and CSRF origins',async()=>{expect((await stranger.call('admin/products')).status).toBe(401);expect((await stranger.call('auth/login','POST',{email:'a@example.com',password:'wrong'},{Origin:'https://attacker.invalid'})).status).toBe(403);});
  it('creates a validated product with two stock units',async()=>{const categories=await admin.call('categories');const result=await admin.call('admin/products','POST',{title:`Verification Bowl ${unique}`,slug:`verification-bowl-${unique}`,subtitle:'Integration fixture',description:'A handcrafted bowl created for isolated integration verification.',categoryId:categories.body.data[0].id,artisan:'Verification Studio',origin:'Jaipur',materials:'Stoneware',care:'Hand wash',dimensions:'10 cm',status:'PUBLISHED',featured:false,images:[{url:'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61',alt:'Verification bowl',position:0}],variants:[{sku:`VERIFY-${unique}`,name:'Natural',price:125000,stock:2,weightGrams:500,active:true}],customizations:[]});expect(result.status).toBe(201);product=(await admin.call(`admin/products/${result.body.data.id}`)).body.data;expect(product.variants[0].inventory.available).toBe(2);});
  it('refuses product mass assignment and customer editing',async()=>{expect((await stranger.call(`admin/products/${product.id}`,'PATCH',{title:'Hacked'})).status).toBe(401);const registration=await stranger.call('auth/register','POST',{email:`verify-${unique}@example.com`,name:'Verification User',password:'Verification!2026'});expect(registration.status).toBe(201);expect((await stranger.call('admin/dashboard')).status).toBe(403);expect((await stranger.call(`admin/products/${product.id}`,'PATCH',{title:'Hacked'})).status).toBe(403);});
  it('isolates bags and rejects a client price',async()=>{await guest.call('cart');expect((await guest.call('cart/items','POST',{variantId:product.variants[0].id,quantity:1,price:1})).status).toBe(422);expect((await guest.call('cart/items','POST',{variantId:product.variants[0].id,quantity:1})).status).toBe(201);expect((await stranger.call('cart')).body.data.items).toHaveLength(0);});
  it('rejects manipulated checkout totals without reserving stock',async()=>{expect((await guest.call('checkout','POST',{email:'guest@example.com',address,idempotencyKey:randomUUID(),total:1})).status).toBe(422);expect((await admin.call(`admin/products/${product.id}`)).body.data.variants[0].inventory.reserved).toBe(0);});
  it('reserves inventory atomically and applies a coupon on the server',async()=>{const idempotencyKey=randomUUID();const input={email:'guest@example.com',address,idempotencyKey,coupon:'WELCOME10'};const result=await guest.call('checkout','POST',input);expect(result.status).toBe(201);order=result.body.data;expect(order.subtotal).toBe(125000);expect(order.discount).toBe(12500);expect(order.total).toBe(122400);const inventory=(await admin.call(`admin/products/${product.id}`)).body.data.variants[0].inventory;expect(inventory.available).toBe(1);expect(inventory.reserved).toBe(1);const retry=await guest.call('checkout','POST',input);expect(retry.status).toBe(201);expect(retry.body.data.id).toBe(order.id);});
  it('prevents order IDOR and does not expose guest access hashes',async()=>{expect((await stranger.call(`orders/${order.id}`)).status).toBe(404);const result=await guest.call(`orders/${order.id}`);expect(result.status).toBe(200);expect(result.body.data.accessTokenHash).toBeUndefined();expect(result.body.data.requestHash).toBeUndefined();});
  it('blocks overselling even when two bags request the last unit',async()=>{const a=new Client(),b=new Client();for(const c of [a,b]){await c.call('cart');expect((await c.call('cart/items','POST',{variantId:product.variants[0].id,quantity:1})).status).toBe(201);}const results=await Promise.all([a,b].map(c=>c.call('checkout','POST',{email:'race@example.com',address,idempotencyKey:randomUUID()})));expect(results.filter(r=>r.status===201)).toHaveLength(1);expect(results.filter(r=>r.status===409)).toHaveLength(1);const winner=results.find(r=>r.status===201)!;await admin.call(`admin/orders/${winner.body.data.id}/status`,'PATCH',{status:'CANCELLED'});expect((await admin.call(`admin/products/${product.id}`)).body.data.variants[0].inventory.available).toBe(1);});
  it('rejects forged payment webhooks and arbitrary paid status',async()=>{expect((await stranger.call('payments/webhook','POST',{event:'payment.captured'},{'x-razorpay-signature':'forged'})).status).toBe(400);expect((await admin.call(`admin/orders/${order.id}/status`,'PATCH',{status:'PAID'})).status).toBe(400);});
  it('captures a development payment once and converts reservation to sale',async()=>{expect((await guest.call(`orders/${order.id}/mock-payment`,'POST')).status).toBe(201);const paid=(await guest.call(`orders/${order.id}`)).body.data;expect(paid.status).toBe('PAID');const inventory=(await admin.call(`admin/products/${product.id}`)).body.data.variants[0].inventory;expect(inventory.reserved).toBe(0);expect(inventory.sold).toBe(1);expect((await guest.call(`orders/${order.id}/mock-payment`,'POST')).status).toBe(409);});
  it('validates fulfillment order and requires shipment tracking',async()=>{expect((await admin.call(`admin/orders/${order.id}/status`,'PATCH',{status:'DELIVERED'})).status).toBe(400);for(const status of ['PROCESSING','PACKED'])expect((await admin.call(`admin/orders/${order.id}/status`,'PATCH',{status})).status).toBe(200);expect((await admin.call(`admin/orders/${order.id}/status`,'PATCH',{status:'SHIPPED'})).status).toBe(400);expect((await admin.call(`admin/orders/${order.id}/status`,'PATCH',{status:'SHIPPED',trackingNumber:`VERIFY-${unique}`})).status).toBe(200);});
  it('rejects SVG disguised as an image',async()=>{const form=new FormData();form.set('file',new Blob(['<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>'],{type:'image/png'}),'image.png');const response=await fetch(`${base}/media`,{method:'POST',headers:{Origin:origin,Cookie:[...admin.cookies].map(([k,v])=>`${k}=${v}`).join('; ')},body:form});expect(response.status).toBe(400);});
  it('handles injection-like catalog queries as data',async()=>{expect((await guest.call(`products?q=${encodeURIComponent("'; DROP TABLE Product; --")}`)).status).toBe(200);expect((await guest.call(`products?q=${encodeURIComponent('<script>alert(1)</script>')}`)).body.data).toHaveLength(0);});
  it('archives the test product without losing order history',async()=>{expect((await admin.call(`admin/products/${product.id}`,'DELETE')).status).toBe(200);expect((await guest.call(`products/${product.slug}`)).status).toBe(404);expect((await guest.call(`orders/${order.id}`)).body.data.items[0].title).toContain('Verification Bowl');});
});
